### ISSUE TITLE
Support for specifying a solution file to load

### ISSUE THREAD

**Issue by razzmatazz** [statiolake/vscode-csharp-ls#1]
csharp-ls support specifying a solution via the `-s` or (`--solution`) param where there are many to be found on project folder.

Is it possible to add a configuration parameter for this?

Thank you!

**Comment by statiolake** [comment]
Maybe supported in v0.1.2. Use `csharp-ls.solution.path` option to specify the solution file. You can use workspace configuration.

**Comment by razzmatazz** [comment]
thanks! it works
