### ISSUE TITLE
Ability to build VSIX file

### ISSUE THREAD

**Issue by razzmatazz** [statiolake/vscode-csharp-ls#3]
It would be nice to be able to work with locally-installed extension via VSIX.

Would you be willing to implement this? It would make development/testing of you extension easier.

Again, https://github.com/vytautassurvila/vscode-csharp-ls has that. Also some kind of README.md on how to build this .vsix file would be helpful.

**Comment by statiolake** [comment]
With [vsce](https://github.com/microsoft/vscode-vsce), you can build .vsix easily.

```console
$ git clone https://github.com/statiolake/vscode-csharp-ls
$ npm install
$ vsce package
```

I'll consider adding this to README.md.

**Comment by NCLnclNCL** [comment]
> It would be nice to be able to work with locally-installed extension via VSIX.
> 
> Would you be willing to implement this? It would make development/testing of you extension easier.
> 
> Again, https://github.com/vytautassurvila/vscode-csharp-ls has that. Also some kind of README.md on how to build this .vsix file would be helpful.

Hey bro, Besides the above 2 extensions and omnisharp, is there any other extension for csharp like this?
